# wordpress + sql compose file | DESATUALIZADO

# versao do compose
version: '3.3'

# serviços
services:

  # container sql
  db:
    # img base
    image: mysql:5.7
    # volumes
    volumes:
      - db_data:/var/lib/mysql
    # salvando alterações automaticamente
    restart: always
    # variaveis de ambiente
    # env_file -> importamos dados sensiveis sem expolos
    env_file:
      - ./config/db.env
    # abaixo, expomos dados sensiveis do projeto
    # environment:
    #   MYSQL_ROOT_PASSWORD: CHANGE_ME
    #   MYSQL_DATABASE: CHANGE_ME
    #   MYSQL_USER: CHANGE_ME
    #   MYSQL_PASSWORD: CHANGE_ME

    # definindo redes para conexão
    networks:
      - backend

  # container wordpress
  wordpress:
    # dependencias necessárias do container
    depends_on:
      - db
    # img base
    image: wordpress:latest
    # portas
    ports:
      - "8000:80"
    # salvando alterações automaticamente
    restart: always
    # variaveis de ambiente
    env_file:
      - ./config/wp.env
    # abaixo, expomos dados sensiveis do projeto
    # environment:
    #   WORDPRESS_DB_HOST: CHANGE-ME
    #   WORDPRESS_DB_USER: CHANGE-ME
    #   WORDPRESS_DB_PASSWORD: CHANGE-ME
    #   WORDPRESS_DB_NAME: CHANGE-ME

    # definindo redes para conexão
    networks:
      - backend

# volumes principais
volumes:
  # iniciando volume vazio
  db_data: {}

# criando redes na inicialização
networks:
  backend:
    # selecionando driver
    driver: bridge
