# versao compose
version: '3.3'

services:
  # container
  db:
    # minha imagem
    # image: my_sql_img

    # podemos indicar a build de uma imagem no compose
    build: ./sql/

    # sempre atualizar
    restart: always
    # dados sigilosos
    env_file:
      - ./config/db.env
    # portas
    ports:
      - "3306:3306"
    # minha network
    networks:
      - flask_network

  backend:
    # container
    # dependencias necessaria
    depends_on:
      - db
    # minha imagem
    # image: my_flask_img

    # podemos indicar a build de uma imagem no compose
    build: ./flask/

    # portas
    ports:
      - "5000:5000"
    # sempre atualizar
    restart: always

    # adicionando bind mount volume
    # path_absoluto:workdir_da_imagem
    volumes:
      - "C:\\Users\\glauc\\OneDrive\\Documents\\git_repos\\docker_studies\\docker_compose\\replicando_projeto\\flask:/app"

    # minha network
    networks:
      - flask_network

# redes
networks:
  flask_network:
    driver: bridge
